export const ROUTES = {
  HOME: '/',
  JOBS: '/jobs',
  SCHOLARSHIPS: '/scholarships',
  ADMISSIONS: '/admissions',
  SCHOOLS_AND_COLLEGES: '/schools-and-colleges',
  FOREIGN_STUDIES: '/foreign-studies',
  BLOG: '/blog',
  CONTACT: '/contact',
  LOGIN: '/auth/login',
  REGISTER: '/auth/register',
  FORGOT_PASSWORD: '/auth/forgot-password',
  RESET_PASSWORD: '/auth/reset-password',
  PROFILE: '/profile',
  DASHBOARD: '/dashboard',
  SAVED_JOBS: '/saved-jobs',
  ADMIN: '/admin',
  RESUME_ANALYZER: '/resume-analyzer',
  EXAM_PREP: '/exam-prep',
  EXAM_DETAIL: '/exam-prep/:slug',
  QUIZ_TAKE: '/exam-prep/quiz/:quizId',
  INTERNSHIPS: '/internships',
  WEBINARS: '/webinars',
  INTL_SCHOLARSHIPS: '/intl-scholarships',
  BADGES_LEADERBOARD: '/badges',
  RESUME_BUILDER: '/resume-builder',
  CAREER_GUIDANCE: '/career-guidance',
  ABOUT: '/about',
  SERVICES: '/services',
  ADVERTISE: '/advertise',
  HELP_CENTER: '/help-center',
  FAQ: '/faq',
  SUBMIT_OPPORTUNITY: '/submit-opportunity',
  PRIVACY_POLICY: '/privacy-policy',
  TERMS: '/terms',
  COOKIES: '/cookies',
  EMPLOYER_LOGIN: '/employer/login',
  EMPLOYER_REGISTER: '/employer/register',
  EMPLOYER_DASHBOARD: '/employer',
  EMPLOYER_JOBS: '/employer/jobs',
  EMPLOYER_POST_JOB: '/employer/jobs/new',
  EMPLOYER_APPLICATIONS: '/employer/applications',
  EMPLOYER_ANALYTICS: '/employer/analytics',
  EMPLOYER_SETTINGS: '/employer/settings',
};

export const ROLES = { ADMIN: 'Admin', USER: 'User' };

export const API_BASE_URL = import.meta.env.VITE_API_URL || 'http://localhost:5000/api';
