/**
 * Auto-generate SEO blog posts from new/scraped listings.
 */
import { Blog } from '../models/Blog.js';
import { Job } from '../models/Job.js';
import { Scholarship } from '../models/Scholarship.js';
import { Admission } from '../models/Admission.js';
import { blogSlug } from '../utils/slugify.js';

function makeBlogSlugUnique(baseSlug, existingSlugs, index = 0) {
  const slug = index === 0 ? baseSlug : `${baseSlug}-${index}`;
  if (existingSlugs.has(slug)) return makeBlogSlugUnique(baseSlug, existingSlugs, index + 1);
  return slug;
}

export async function generateBlogFromListings(options = {}) {
  const { jobIds = [], scholarshipIds = [], admissionIds = [], title: customTitle, maxListings = 10 } = options;
  const existingSlugs = new Set((await Blog.find({}).select('slug').lean()).map((b) => b.slug));

  const jobs = jobIds.length
    ? await Job.find({ _id: { $in: jobIds }, status: 'active' }).limit(maxListings).lean()
    : await Job.find({ status: 'active' }).sort({ scrapedAt: -1, createdAt: -1 }).limit(5).lean();
  const scholarships = scholarshipIds.length
    ? await Scholarship.find({ _id: { $in: scholarshipIds }, status: 'active' }).limit(5).lean()
    : await Scholarship.find({ status: 'active' }).sort({ deadline: 1 }).limit(3).lean();
  const admissions = admissionIds.length
    ? await Admission.find({ _id: { $in: admissionIds }, status: 'active' }).limit(5).lean()
    : await Admission.find({ status: 'active' }).sort({ deadline: 1 }).limit(3).lean();

  const title = customTitle || `Latest Opportunities – Jobs, Scholarships & Admissions (${new Date().toISOString().slice(0, 10)})`;
  const excerpt = `Curated list of new jobs, scholarships, and admission deadlines for students and job seekers in Pakistan.`;
  const tags = ['jobs', 'scholarships', 'admissions', 'Pakistan', 'opportunities', 'students'];
  const category = 'Opportunities';

  const jobLinks = jobs.map((j) => `- [${j.title}](${j.organization || j.company}) – ${j.province || ''}`).join('\n');
  const scholarshipLinks = scholarships.map((s) => `- [${s.title}](${s.provider}) – Deadline: ${s.deadline ? new Date(s.deadline).toLocaleDateString() : 'N/A'}`).join('\n');
  const admissionLinks = admissions.map((a) => `- [${a.program} – ${a.institution}] – ${a.province || ''}`).join('\n');

  const content = `
## New Jobs
${jobLinks || '_No new jobs this time._'}

## Trending Scholarships
${scholarshipLinks || '_Check back soon._'}

## Admission Deadlines
${admissionLinks || '_No upcoming deadlines._'}

---
*Auto-generated by EduRozgaar. Stay updated for more opportunities.*
  `.trim();

  const baseSlug = blogSlug(title);
  const slug = makeBlogSlugUnique(baseSlug, existingSlugs);
  const metaDescription = excerpt.slice(0, 160);

  const blog = await Blog.create({
    title,
    slug,
    excerpt,
    content,
    tags,
    category,
    status: 'published',
    publishedAt: new Date(),
    views: 0,
  });

  return {
    blog: { _id: blog._id, title: blog.title, slug: blog.slug, excerpt: blog.excerpt, tags: blog.tags, category: blog.category },
    seo: { title, metaDescription, keywords: tags.join(', ') },
  };
}
