/**
 * Phase-8 seed: sample scraped jobs, auto-generated blogs, newsletter logs.
 * Run after seedPhase4/5/7. From server: node src/scripts/seedPhase8.js
 */
import 'dotenv/config';
import mongoose from 'mongoose';
import { Job } from '../models/Job.js';
import { Admission } from '../models/Admission.js';
import { Blog } from '../models/Blog.js';
import { NewsletterLog } from '../models/NewsletterLog.js';
import { jobSlug } from '../utils/slugify.js';
import { admissionSlug } from '../utils/slugify.js';
import { blogSlug } from '../utils/slugify.js';

const MONGO_URI = process.env.MONGO_URI || 'mongodb://localhost:27017/edurozgaar';

const SCRAPED_JOBS = [
  { title: 'PPSC Lecturer Biology 2024', company: 'PPSC', province: 'Punjab', category: 'Government', sourceUrl: 'https://www.ppsc.gop.pk' },
  { title: 'FPSC Assistant Director', company: 'FPSC', province: 'Punjab', category: 'Government', sourceUrl: 'https://www.fpsc.gov.pk' },
  { title: 'NTS Project Coordinator', company: 'NTS', province: 'Punjab', category: 'Government', sourceUrl: 'https://www.nts.org.pk' },
  { title: 'WAPDA Engineer Civil', company: 'WAPDA', province: 'Punjab', category: 'Engineering', sourceUrl: 'https://www.wapda.gov.pk' },
  { title: 'Punjab Police SI Recruitment', company: 'Punjab Police', province: 'Punjab', category: 'Government', sourceUrl: 'https://punjabpolice.gov.pk' },
  { title: 'PPSC Medical Officer', company: 'PPSC', province: 'Punjab', category: 'Government', sourceUrl: 'https://www.ppsc.gop.pk' },
  { title: 'FPSC CSS 2024', company: 'FPSC', province: 'Punjab', category: 'Government', sourceUrl: 'https://www.fpsc.gov.pk' },
  { title: 'NTS Data Entry Operator', company: 'NTS', province: 'Sindh', category: 'Government', sourceUrl: 'https://www.nts.org.pk' },
  { title: 'WAPDA IT Specialist', company: 'WAPDA', province: 'Punjab', category: 'IT', sourceUrl: 'https://www.wapda.gov.pk' },
  { title: 'Punjab Police Constable', company: 'Punjab Police', province: 'Punjab', category: 'Government', sourceUrl: 'https://punjabpolice.gov.pk' },
];

const SCRAPED_ADMISSIONS = [
  { program: 'BS Computer Science 2024', institution: 'University of Punjab', province: 'Punjab', sourceUrl: 'https://pu.edu.pk' },
  { program: 'BSc Engineering Admissions', institution: 'UET Lahore', province: 'Punjab', sourceUrl: 'https://uet.edu.pk' },
];

async function ensureSlugUnique(Model, baseSlug, field = 'slug') {
  const existing = await Model.findOne({ [field]: baseSlug });
  if (!existing) return baseSlug;
  let i = 1;
  while (await Model.findOne({ [field]: `${baseSlug}-${i}` })) i++;
  return `${baseSlug}-${i}`;
}

async function seed() {
  await mongoose.connect(MONGO_URI);
  const scrapedAt = new Date();

  for (const j of SCRAPED_JOBS) {
    const baseSlug = jobSlug(j.title, j.province || '');
    const slug = await ensureSlugUnique(Job, baseSlug);
    await Job.findOneAndUpdate(
      { title: j.title, company: j.company },
      {
        $setOnInsert: {
          title: j.title,
          slug,
          company: j.company,
          organization: j.company,
          province: j.province,
          category: j.category,
          type: 'full-time',
          status: 'active',
          source: 'scraper',
          scrapedAt,
          sourceUrl: j.sourceUrl,
        },
      },
      { upsert: true }
    );
  }
  console.log('Scraped jobs:', SCRAPED_JOBS.length);

  for (const a of SCRAPED_ADMISSIONS) {
    const baseSlug = admissionSlug(a.program, a.institution);
    const slug = await ensureSlugUnique(Admission, baseSlug);
    await Admission.findOneAndUpdate(
      { program: a.program, institution: a.institution },
      {
        $setOnInsert: {
          program: a.program,
          slug,
          institution: a.institution,
          province: a.province,
          status: 'active',
          source: 'scraper',
          scrapedAt,
          sourceUrl: a.sourceUrl,
        },
      },
      { upsert: true }
    );
  }
  console.log('Scraped admissions:', SCRAPED_ADMISSIONS.length);

  for (let i = 1; i <= 5; i++) {
    const title = `Latest Opportunities Round ${i} – Jobs & Admissions`;
    const baseSlug = blogSlug(title) + (i > 1 ? `-${i}` : '');
    const slug = await ensureSlugUnique(Blog, baseSlug);
    await Blog.findOneAndUpdate(
      { slug },
      {
        $setOnInsert: {
          title,
          slug,
          excerpt: `Auto-generated roundup of new jobs and admission deadlines for students in Pakistan.`,
          content: `## New jobs and admissions\n\nCheck the Jobs and Admissions pages for the latest listings.\n\n*Generated by EduRozgaar.*`,
          tags: ['jobs', 'admissions', 'Pakistan', 'opportunities'],
          category: 'Opportunities',
          status: 'published',
          publishedAt: new Date(),
        },
      },
      { upsert: true }
    );
  }
  console.log('Auto-generated blogs: 5');

  for (let i = 0; i < 5; i++) {
    const d = new Date();
    d.setDate(d.getDate() - i);
    await NewsletterLog.create({
      sentAt: d,
      subscriberCount: 10 + i,
      sentCount: 10 + i,
      openCount: 3 + i,
      clickCount: 1 + i,
      subject: `EduRozgaar Daily – ${d.toISOString().slice(0, 10)}`,
      summary: `New jobs, scholarships, admissions.`,
      status: 'sent',
    });
  }
  console.log('Newsletter logs: 5');

  await mongoose.disconnect();
  console.log('Phase-8 seed done.');
}

seed().catch((err) => {
  console.error(err);
  process.exit(1);
});
